// <auto-generated />
using System;
using DotNetApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetApi.Migrations
{
    [DbContext(typeof(PoetryDBContext))]
    [Migration("20230326103741_SeededSomeDataToDB")]
    partial class SeededSomeDataToDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetApi.Models.Poet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Poets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDay = new DateTime(1355, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hafez"
                        },
                        new
                        {
                            Id = 2,
                            BirthDay = new DateTime(1207, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Molana"
                        });
                });

            modelBuilder.Entity("DotNetApi.Models.Poetry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PoetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PoetId");

                    b.ToTable("Poetries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "مثنوی معنوی",
                            Name = "Masnavi manavi",
                            PoetId = 2
                        });
                });

            modelBuilder.Entity("DotNetApi.Models.Poetry", b =>
                {
                    b.HasOne("DotNetApi.Models.Poet", "Poet")
                        .WithMany("Poetries")
                        .HasForeignKey("PoetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poet");
                });

            modelBuilder.Entity("DotNetApi.Models.Poet", b =>
                {
                    b.Navigation("Poetries");
                });
#pragma warning restore 612, 618
        }
    }
}
